---
title: "Labels and Containers"
output:
  pdf_document: default
  html_notebook: default
---


### Instruction

 1. This activity builds on the code you wrote for the first milestone, which shows an apparent inconsistency in the 
behavior of Python variables.

    - The key in this activity will be to use the id() function to compare the unique ID numbers of all the variables
    as you create and change them.

2. Write code to try to prove whether the container model or the label model best describes the behavior of variables
in Python. Again, using the id() function is key.

3. State your understanding of how Python variables work in a few sentences.

4. Variable types: int, float, string, list, tuple and dictionary

### 1 - Integer (int)

```{python}
# Creating the int
x = 25  # x is a label and 25 is a object / variables are labels which can be attached to objects in memory.

# Creating a second variable int equal to the first
y = x  # y is a label and x is a object and so object and label are value.

# Printing
print(x, y)
print(id(x))
print(id(y))
print( "x and y are actually referring to the same object 25 \n")

# Changing the second int variable
x = [10, 20, 30]  # here we are building a new object for x

print(f'value of x: {x} ID of x: {id(x)}')
print(f'value of x[0]: {x[0]} ID of x: {id(x[0])}')
print(f'value of x[1]: {x[1]} ID of x: {id(x[1])}')
print(f'value of x[2]: {x[2]} ID of x: {id(x[2])}')
print("x is referring to the different object ")
```

### 2 - Float¶

```{python}
x = 25.25
y = x

print(id(x))
print(id(y))

x = [10.2 , 20.3 , 30.25]
print(f'value of x: {x} ID of x: {id(x)}') 
```

### 3 - String

```{python}
a = "name"
b = a

print(id(a))
print(id(b))

b = ["Mary"," Paty", "Ale"]
print(f' value of b: {b} ID of b: {id(b)}')
```

### 4 - List

```{python}
# Creating the List
List1 =  [1, 5.2, 9, 12, 24, 33]

# Creating a second variable List equal to the first
List2 = List1 

# Printing
print(id(List1))
print(id(List2))

# Changing the second List variable
List2 = [1968,"car","model" ]

# Printing
print(f"Value of List1: {List1} ID of List1: {id(List1)}")
print(f"Value of List2: {List2} ID of List2: {id(List2)}")
print(f"Value of List2[1]: {List2[1]} ID of List2[1]: {id(List2[1])}")

```

### 5 - Tuple

```{python}
# Creating a variable tuple
tuple1 = (57, "birthday", 1964, "weight",[1965, 1964, 1963])

# Creating a second variable tuple equal to the first
tuple2 = tuple1

# printing
print(id(tuple1))
print(id(tuple2))

print ('Tuple is immutable variable')

# 1.3) Changing the second variable
tuple2[3] = 89

```

```{python}
# Creating a variable tuple
tuple1 = (57, "birthday", 1964, "weight",[1965, 1964, 1963])

# Creating a second variable tuple equal to the first
tuple2 = tuple1

# printing
print(id(tuple1))
print(id(tuple2))

print ('Tuple is immutable variable')

# 1.3) Changing the second variable
tuple2 = (2.0, "name", "whatever")
print(f"Value of tupl2[1]: {tuple2[1]} ID of tuple2[1]: {id(tuple2[1])}")
```

### 6 - Dictionary

```{python}
# Creating the dictionary
Dict1 = {"key1": 1, "key2": "2", "key3": [3, 3, 3], "key4": "quatro"}

# Creating a second variable dictionay equal to the first
Dict2 = Dict1

# Printing
print(id(Dict1))
print(id(Dict2))

# Changing the second dictionay variable
Dict2["key1"] = "new value" # here we are building a new object. Append value with key into dictionary

print(f'Value of Dict2["key1"]: {Dict2["key1"]} ID of Dict2["key1"]: {id(Dict2["key1"])}')
```

### Conclusion:
#### Python is a programming language that supports OOP. The variables are labels which can be attached to objects in memory, wherever they are.



